let base = {
    applicant: {
        certificationNo: {
            cprop: {
                rules: 'email',
                tag: 'div',
                name: '证件号码',
            },
            show: true,
            inputType: 'input',
            path: 'certificationNo',
            label: '证件号码',
            value: '',
            readonly: false,
            placeholder: '',
            required: true,
            suffix: '',
        },
        certificationNo2: {
            show: true,
            inputType: 'input',
            path: 'certificationNo',
            label: '证件号码',
            value: '',
            readonly: false,
            placeholder: '',
            required: true,
            suffix: '',
        },
        certificationType: {
            show: true,
            inputType: 'select',
            path: 'certificationType',
            label: '证件类型',
            value: '1',
            readonly: false,
            placeholder: '',
            required: true,
            suffix: '',
            list: [{
                    value: '1',
                    text: '身份证',
                },
                {
                    value: '2',
                    text: '护照',
                },
            ],
        },
    },
    insured: [],
    extend: {},
    specileRYX: {},
    specile: {},
};