let base = {
    sameTB: false,
    applicant: {
        name: {
            cprop: {
                rules: {
                    chineseName: [2, 10],
                    required: true,
                },
                name: '姓名',
                vid: 'name',
            },
            show: true,
            inputType: 'input',
            path: 'personName',
            label: '姓名',
            value: '',
            readonly: false,
            placeholder: '',
            required: true,
            suffix: '',
        },
        card: {
            cprop: {
                rules: {
                    required: true,
                    cardNo: ['@cardType', '@parent'],
                },
                name: '证件号码',
                vid: 'card',
            },
            show: true,
            inputType: 'input',
            path: 'certificationNo',
            label: '证件号码',
            value: '',
            readonly: false,
            placeholder: '',
            required: true,
            suffix: '',
        },
        birthday: {
            cprop: {
                name: '出生日期',
                vid: 'birthday',
            },
            show: true,
            inputType: 'datetime',
            path: 'certificationNo',
            label: '出生日期',
            value: '',
            readonly: false,
            placeholder: '',
            required: true,
            suffix: '',
        },
        shebao: {
            cprop: {
                name: '社保',
                vid: 'shebao',
            },
            show: true,
            inputType: 'input',
            path: 'certificationNo',
            label: '社保',
            value: '',
            readonly: false,
            placeholder: '',
            required: true,
            suffix: '',
        },
        ctype: {
            cprop: {
                vid: 'cardType',
            },
            show: true,
            inputType: 'select',
            path: 'certificationType',
            label: '证件类型',
            value: '1',
            readonly: false,
            placeholder: '',
            required: true,
            suffix: '',
            list: [{
                    value: '1',
                    text: '身份证',
                },
                {
                    value: '2',
                    text: '护照',
                },
            ],
        },
        phone: {
            cprop: {
                rules: {
                    required: true,
                    checkPhoneNo: true,
                },
                name: '手机号',
            },
            show: true,
            inputType: 'input',
            path: 'certificationNo',
            label: '手机号',
            type: 'phone',
            value: '',
            readonly: false,
            placeholder: '',
            required: true,
            suffix: '',
        },
        eamil: {
            cprop: {
                rules: {
                    email: '',
                },
            },
            show: true,
            inputType: 'input',
            path: 'certificationNo',
            label: '邮箱',
            value: '',
            readonly: false,
            placeholder: '',
            required: true,
            suffix: '',
        },
    },
    insured: [{
        name: {
            cprop: {
                rules: {
                    chineseName: [2, 10],
                    required: true,
                },
                name: '姓名',
                vid: 'name',
            },
            show: true,
            inputType: 'input',
            path: 'personName',
            label: '姓名',
            value: '',
            readonly: false,
            placeholder: '',
            required: true,
            suffix: '',
        },
        card: {
            cprop: {
                rules: {
                    required: true,
                    cardNo: ['@cardType', '@parent'],
                },
                name: '证件号码',
                vid: 'card',
            },
            show: true,
            inputType: 'input',
            path: 'certificationNo',
            label: '证件号码',
            value: '',
            readonly: false,
            placeholder: '',
            required: true,
            suffix: '',
        },
        birthday: {
            cprop: {
                name: '出生日期',
                vid: 'birthday',
            },
            show: true,
            inputType: 'datetime',
            path: 'certificationNo',
            label: '出生日期',
            value: '',
            readonly: false,
            placeholder: '',
            required: true,
            suffix: '',
        },
        shebao: {
            cprop: {
                name: '社保',
                vid: 'shebao',
            },
            show: true,
            inputType: 'input',
            path: 'certificationNo',
            label: '社保',
            value: '',
            readonly: false,
            placeholder: '',
            required: true,
            suffix: '',
        },
        ctype: {
            cprop: {
                vid: 'cardType',
            },
            show: true,
            inputType: 'select',
            path: 'certificationType',
            label: '证件类型',
            value: '1',
            readonly: false,
            placeholder: '',
            required: true,
            suffix: '',
            list: [{
                    value: '1',
                    text: '身份证',
                },
                {
                    value: '2',
                    text: '护照',
                },
            ],
        },
        phone: {
            cprop: {
                rules: {
                    required: true,
                    checkPhoneNo: true,
                },
                name: '手机号',
            },
            show: true,
            inputType: 'input',
            path: 'certificationNo',
            label: '手机号',
            type: 'phone',
            value: '',
            readonly: false,
            placeholder: '',
            required: false,
            suffix: '',
        },
    }, ],
    extend: {},
    specileRYX: {},
    specile: {},
};